# Generated by Django 4.1 on 2022-08-31 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BlogName', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='about')),
                ('subtitle', models.TextField(max_length=500)),
                ('aboutme', models.TextField(max_length=10000)),
                ('tw_account', models.URLField()),
                ('fb_account', models.URLField()),
                ('ins_account', models.URLField()),
                ('link_account', models.URLField()),
            ],
        ),
    ]
